/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData robot_arm =
      IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad =
      IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_list =
      IconData(0xf46d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit =
      IconData(0xf4ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData robot =
      IconData(0xf544, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
